INSERT INTO vocabulary(textbook_id, english_example_sentence1, korean_example_sentence1, english_example_sentence2,
                       korean_example_sentence2, english_vocabulary, korean_vocabulary, pronunciation)
VALUES (1,
        'Drive slowly.', '천천히 운전하다.',
        'Drive a car.', '자동차를 운전하다.',
        'To drive', '운전하다', 'Unjeonhada'),
       (1,
        'The taxi driver is kind.', '택시 운전사가 친절하다.',
        'The bus driver honks the horn.', '버스 운전사가 경적을 울리다.',
        'Driver', '운전사', 'Unjeonsa'),
       (1,
        'Use the airport bus.', '공항버스를 이용하다.',
        'Use the library.', '도서관을 이용하다.',
        'To use', '이용하다', 'Iyonghada'),
       (1,
        'There are many cars on the street.', '거리에 자동차가 많다.',
        'The car drives fast.', '자동차가 빠르게 달린다.',
        'Car', '자동차', 'Jadongcha'),
       (1,
        'The train departs on time.', '기차가 정시에 출발한다.',
        'The bus just left.', '방금 버스가 출발했다.',
        'To depart', '출발하다', 'Chulbalhada'),
       (1,
        'There is a store across the street.', '길 건너에 가게가 있다.',
        'There is a lot of trash on the road.', '길에 쓰레기가 많다.',
        'Street / Road', '길', 'Gil');
