spring:
  application:
    name: backend

  profiles:
    active: ${ SPRING_PROFILES_ACTIVE:dev }

google:
  meet:
    baseUrl: https://meet.googleapis.com
  oauth:
    baseUrl: https://accounts.google.com