spring:
  application:
    name: backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  baseurl: ${SPRING_BASEURL:http://localhost:8080}

google:
  meet:
    baseUrl: https://meet.googleapis.com
  oauth:
    baseUrl: https://accounts.google.com